export { default as Admin } from "./Admin";
export { default as Applicant } from "./Applicant";
export { default as Dashboard } from "./Dashboard";
export { default as Login } from "./Login";
export { default as Police } from "./Police";
export { default as Register } from "./Register";
export { default as NotFound } from "./NotFound";
export { default as Navbar } from "./Navbar";
export { default as Dropdown } from "./Dropdown"
